name: Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install JavaScript dependencies
        run: yarn install
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, php-cs-fixer
      - name: Check code-style issues
        run: php-cs-fixer fix --diff --dry-run -vvv
      - name: Bundle frontend
        run: npx parcel build src/index.html
      - name: Bundle frontend + backend
        run: php bundle.php
        if: startsWith(github.ref, 'refs/tags/')
      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
